In [2]:
import copy
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

#读取数据
data=pd.read_excel('C:/Users/马嘉文/Desktop/demo.xls')
#print(data)
label_need=data.keys()[1:]
#print(label_need)
#data=data(2:end) #%只取指标数据
data1=data[label_need].values
print(data1)

[[9.67540997e+00 1.42000000e+02 5.35402000e+05 2.72001500e+06]
 [9.56814932e+00 1.71000000e+02 4.31695000e+05 2.01577300e+06]
 [9.46974911e+00 1.42000000e+02 3.43153000e+05 2.04105500e+06]
 [9.37037334e+00 1.94000000e+02 3.41855000e+05 2.00020300e+06]
 [9.37282067e+00 1.10000000e+02 3.74931000e+05 2.18256000e+06]
 [9.54913478e+00 1.16000000e+02 2.75386000e+05 1.25288700e+06]
 [9.37198321e+00 1.25000000e+02 3.95160000e+05 2.11657300e+06]
 [9.53928400e+00 1.95000000e+02 1.74559000e+05 1.04555800e+06]
 [9.36965125e+00 1.48000000e+02 3.86015000e+05 1.95201700e+06]
 [9.36462600e+00 1.69000000e+02 4.12938000e+05 1.67116100e+06]
 [9.35574777e+00 9.30000000e+01 2.93950000e+05 1.33086400e+06]
 [9.26412282e+00 1.03000000e+02 3.15640000e+05 1.57769000e+06]
 [9.26440107e+00 1.65000000e+02 3.21698000e+05 1.59021700e+06]
 [9.16930452e+00 1.71000000e+02 3.51477000e+05 1.76679500e+06]
 [9.25486844e+00 9.80000000e+01 2.25933000e+05 1.24905300e+06]
 [9.25425176e+00 9.70000000e+01 2.13975000e+05 1.231879

In [3]:
#正向化
#指标正向    化处理后数据为data2
data2=data1
print(data2)

[[9.67540997e+00 1.42000000e+02 5.35402000e+05 2.72001500e+06]
 [9.56814932e+00 1.71000000e+02 4.31695000e+05 2.01577300e+06]
 [9.46974911e+00 1.42000000e+02 3.43153000e+05 2.04105500e+06]
 [9.37037334e+00 1.94000000e+02 3.41855000e+05 2.00020300e+06]
 [9.37282067e+00 1.10000000e+02 3.74931000e+05 2.18256000e+06]
 [9.54913478e+00 1.16000000e+02 2.75386000e+05 1.25288700e+06]
 [9.37198321e+00 1.25000000e+02 3.95160000e+05 2.11657300e+06]
 [9.53928400e+00 1.95000000e+02 1.74559000e+05 1.04555800e+06]
 [9.36965125e+00 1.48000000e+02 3.86015000e+05 1.95201700e+06]
 [9.36462600e+00 1.69000000e+02 4.12938000e+05 1.67116100e+06]
 [9.35574777e+00 9.30000000e+01 2.93950000e+05 1.33086400e+06]
 [9.26412282e+00 1.03000000e+02 3.15640000e+05 1.57769000e+06]
 [9.26440107e+00 1.65000000e+02 3.21698000e+05 1.59021700e+06]
 [9.16930452e+00 1.71000000e+02 3.51477000e+05 1.76679500e+06]
 [9.25486844e+00 9.80000000e+01 2.25933000e+05 1.24905300e+06]
 [9.25425176e+00 9.70000000e+01 2.13975000e+05 1.231879

In [4]:
#正向化
#某点最优型指标
index1=[1] 
a=120    #最优型数值
for i in range(0,len(index1)):
    data2[:,index1[i]]=1-abs(data1[:,index1[i]]-a)/max(abs(data1[:,index1[i]]-a))
print(data2)

[[9.67540997e+00 8.13559322e-01 5.35402000e+05 2.72001500e+06]
 [9.56814932e+00 5.67796610e-01 4.31695000e+05 2.01577300e+06]
 [9.46974911e+00 8.13559322e-01 3.43153000e+05 2.04105500e+06]
 [9.37037334e+00 3.72881356e-01 3.41855000e+05 2.00020300e+06]
 [9.37282067e+00 9.15254237e-01 3.74931000e+05 2.18256000e+06]
 [9.54913478e+00 9.66101695e-01 2.75386000e+05 1.25288700e+06]
 [9.37198321e+00 9.57627119e-01 3.95160000e+05 2.11657300e+06]
 [9.53928400e+00 3.64406780e-01 1.74559000e+05 1.04555800e+06]
 [9.36965125e+00 7.62711864e-01 3.86015000e+05 1.95201700e+06]
 [9.36462600e+00 5.84745763e-01 4.12938000e+05 1.67116100e+06]
 [9.35574777e+00 7.71186441e-01 2.93950000e+05 1.33086400e+06]
 [9.26412282e+00 8.55932203e-01 3.15640000e+05 1.57769000e+06]
 [9.26440107e+00 6.18644068e-01 3.21698000e+05 1.59021700e+06]
 [9.16930452e+00 5.67796610e-01 3.51477000e+05 1.76679500e+06]
 [9.25486844e+00 8.13559322e-01 2.25933000e+05 1.24905300e+06]
 [9.25425176e+00 8.05084746e-01 2.13975000e+05 1.231879

In [5]:
#0.002~1区间归一化
[m,n]=data2.shape
data3=copy.deepcopy(data2)
ymin=0.002
ymax=1
for j in range(0,n):
    d_max=max(data2[:,j])
    d_min=min(data2[:,j])
    data3[:,j]=(ymax-ymin)*(data2[:,j]-d_min)/(d_max-d_min)+ymin
#print(data3)
data4 = DataFrame(data3,columns=['score','duration','comments','rating_num'])
data4.to_excel('C:/Users/马嘉文/Desktop/test2.xlsx', sheet_name='Sheet1', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None, merge_cells=True, encoding=None, inf_rep='inf', verbose=True, freeze_panes=None)

In [6]:
#计算信息熵
p=copy.deepcopy(data3)
for j in range(0,n):
    p[:,j]=data3[:,j]/sum(data3[:,j])
print(p)
E=copy.deepcopy(data3[0,:])
for j in range(0,n):
    E[j]=-1/np.log(m)*sum(p[:,j]*np.log(p[:,j]))
print(E)

[[1.08808166e-02 3.98377290e-03 1.71526330e-02 1.75471617e-02]
 [9.99602809e-03 2.78329858e-03 1.36482747e-02 1.28147945e-02]
 [9.18432891e-03 3.98377290e-03 1.06563561e-02 1.29846846e-02]
 [8.36458239e-03 1.83119826e-03 1.06124955e-02 1.27101672e-02]
 [8.38477032e-03 4.48052089e-03 1.17301650e-02 1.39355702e-02]
 [9.83917795e-03 4.72889489e-03 8.36644462e-03 7.68835129e-03]
 [8.37786215e-03 4.68749922e-03 1.24137222e-02 1.34921506e-02]
 [9.75791926e-03 1.78980260e-03 4.95940422e-03 6.29514136e-03]
 [8.35862588e-03 3.73539890e-03 1.21047039e-02 1.23863668e-02]
 [8.31717282e-03 2.86608991e-03 1.30144578e-02 1.04990700e-02]
 [8.24393672e-03 3.77679457e-03 8.99373987e-03 8.21234133e-03]
 [7.48812635e-03 4.19075123e-03 9.72666564e-03 9.87096330e-03]
 [7.49042162e-03 3.03167258e-03 9.93137123e-03 9.95514226e-03]
 [6.70597426e-03 2.78329858e-03 1.09376320e-02 1.11417115e-02]
 [7.41178737e-03 3.98377290e-03 6.69538063e-03 7.66258757e-03]
 [7.40670042e-03 3.94237723e-03 6.29130842e-03 7.547181

In [7]:
# 计算权重
w=(1-E)/sum(1-E)
print(w)

[0.21754368 0.04045323 0.39580811 0.34619498]


In [8]:
#计算得分
s=np.dot(data3,w)
Score=100*s/max(s)
for i in range(0,len(Score)):
    print(f"第{i}个评价对象得分为：{Score[i]}")

第0个评价对象得分为：100.0
第1个评价对象得分为：79.66252109639552
第2个评价对象得分为：72.40840109703203
第3个评价对象得分为：68.31672000333062
第4个评价对象得分为：75.59831836484214
第5个评价对象得分为：58.495319669110216
第6个评价对象得分为：76.46460856888943
第7个评价对象得分为：45.192860045737106
第8个评价对象得分为：72.71629208549189
第9个评价对象得分为：70.2723195121068
第10个评价对象得分为：56.988971057668536
第11个评价对象得分为：60.81240783596135
第12个评价对象得分为：60.495072260124026
第13个评价对象得分为：63.40637371994224
第14个评价对象得分为：49.04828336657598
第15个评价对象得分为：47.834652291903566
第16个评价对象得分为：47.89145004089944
第17个评价对象得分为：66.4511016050255
第18个评价对象得分为：51.67415508134596
第19个评价对象得分为：37.042449943494304
第20个评价对象得分为：43.016603485726726
第21个评价对象得分为：37.51644916997385
第22个评价对象得分为：51.479314568871395
第23个评价对象得分为：46.56550560430408
第24个评价对象得分为：66.41866497132082
第25个评价对象得分为：46.17715809759531
第26个评价对象得分为：37.767074793059294
第27个评价对象得分为：64.29986986280959
第28个评价对象得分为：39.43942577775263
第29个评价对象得分为：38.311247108089574
第30个评价对象得分为：40.93290127588188
第31个评价对象得分为：30.749997455177787
第32个评价对象得分为：30.86770963105815
第33个评价对象得分为：34.17533432